server:
  applicationConnectors:
    - type: ${SERVER_APP_CONNECTOR:-http}
      port: ${SERVER_APP_PORT:-3004}
  adminConnectors:
    - type: ${SERVER_ADMIN_CONNECTOR:-http}
      port: ${SERVER_ADMIN_PORT:-0}
  requestLog:
    type: ${SERVER_REQUEST_LOG_TYPE:-external}

sessionExpiryTimeInSeconds: ${SESSION_EXPIRY_TIME_IN_SECONDS:-1800}

imageReplayExpirySeconds: ${IMAGE_REPLAY_EXPIRY_SECONDS:-50000}
maxAllowedImageReplay: ${MAX_ALLOWED_IMAGE_REPLAY:-10000}
imageHashSalt: ${IMAGE_HASH_SALT:-NoNeedForAPerEnvHash}

redisStoreURI: ${REDIS_STORE_URI}
redisEncryptMessages: ${REDIS_ENCRYPT_MESSAGES:-true}
redisEncryptionTransit: ${REDIS_ENCRYPTION_TRANSIT:-false}

redisKmsCryptoConfiguration:
  kmsEndpointOverride: ${KMS_ENDPOINT_OVERRIDE:-null}
  dataKeyRequestId: ${REDIS_DATA_KEY_REQUESTID}

snsKmsCryptoConfiguration:
  kmsEndpointOverride: ${KMS_ENDPOINT_OVERRIDE:-null}
  dataKeyRequestId: ${SNS_DATA_KEY_REQUEST_ID}

snsTopicName: ${SNS_TOPIC_NAME}
snsRoutingKey: ${SNS_ROUTING_KEY}
snsSubject: ${SNS_SUBJECT}
snsEncryptMessages: ${SNS_ENCRYPT_MESSAGES:-true}

snsConfiguration:
  s3EndpointOverride: ${S3_ENDPOINT_OVERRIDE:-null}
  endpointOverride: ${ENDPOINT_OVERRIDE:-null}
  largePayloadSupportEnabled: ${LARGE_PAYLOAD_SUPPORT_ENABLED:-true}
  pathStyleAccessEnabled: ${PATH_STYLE_ACCESS_ENABLED:-true}
  s3BucketName: ${S3_BUCKET_NAME}
  region: ${REGION:-eu-west-2}

ocrChecksEnabled: ${OCR_CHECKS_ENABLED:-true}
forceLandscapeImageSubmission: ${FORCE_LANDSCAPE_IMAGE_SUBMISSION:-false}
tesseractFolderPath: /tessdata
ocrVerticalSlice: ${OCR_VERTICAL_SLICE:-6}

rejectingOversizeImages: ${REJECTING_OVERSIZE_IMAGES:-true}
targetImageSizeKB: ${TARGET_IMAGE_SIZE_KB:-500}
greyScale: ${GREY_SCALE:-true}

pdfScanDPI: ${PDF_SCAN_DPI:-150}
scanTargetImageSize: ${SCAN_TARGET_IMAGE_SIZE:-1000}

highTarget: ${HIGH_TARGET:-100}
diagonalTarget: ${DIAGONAL_TARGET:-20}
diagonalTargetStrict: ${DIAGONAL_TARGET_STRICT:-50}
strictTarget: ${STRICT_TARGET:-70}

maxLogChars: ${MAX_LOG_CHARS:-50}
targetBrightness: ${TARGET_BRIGHTNESS:-178}
borderLossPercentage: ${BORDER_LOSS_PERCENTAGE:-10}
contrastCutOff: ${CONTRAST_CUT_OFF:-105}

estimatedRequestMemoryMb: ${ESTIMATED_REQUEST_MEMORY_MB:-100}

topLeftText:
  - "Fitness for work"
topRightText:
  - "What your advice means"
  - "Help getting back"
  - "what to do now"
baseLeftText:
  - "Unique ID: Med 3"
baseRightText:
  - "make a claim"
  - "signed this"
baseRightAltText:
  - "healthcare professional"
  - "form to the office dealing"

dataMatrixCreatorServiceUrl: ${DATA_MATRIX_CREATOR_SERVICE_URL:-http://localhost:3009/generate-data-matrix}
dataMatrixCreatorTruststoreFile: ${DATA_MATRIX_CREATOR_TRUSTSTORE_FILE:-null}
dataMatrixCreatorTruststorePass: ${DATA_MATRIX_CREATOR_TRUSTSTORE_PASS:-null}
dataMatrixCreatorKeystoreFile: ${DATA_MATRIX_CREATOR_KEYSTORE_FILE:-null}
dataMatrixCreatorKeystorePass: ${DATA_MATRIX_CREATOR_KEYSTORE_PASS:-null}

logging:
  type: ${LOGGING_TYPE:-external}

applicationInfoEnabled: ${APPLICATION_INFO_ENABLED:-false}
