version: '3.0'

services:

  pi-tests:
    image: ${MAVEN_IMAGE}
    entrypoint: /bin/bash -c
    command:
      - |
        mvn compile test-compile org.pitest:pitest-maven:mutationCoverage -Dverbose -Dthreads=6  -DexcludedTestClasses=uk.gov.dwp.health.fitnotecontroller.utils.fitnotes*,uk.gov.dwp.health.fitnotecontroller.utils.OcrCheckerTest,uk.gov.dwp.health.fitnotecontroller.integration*
    working_dir: /usr/src
    volumes:
      - .:/usr/src
      - ${MVN_M2}:/root/.m2
      - ${MVN_SETTINGS_FILE}:/root/.m2/settings.xml
    environment:
      - JVM_OPTS=-Xmx12g -Xms12g -XX:-UseSplitVerifier
      - IP=0.0.0.0
      - TESSDATA_PREFIX=/usr/src/main/properties/tessdata/
