# Documentation can be found here https://github.com/GoogleContainerTools/container-structure-test
schemaVersion: "2.0.0"

fileExistenceTests:
  - name: 'Jar File'
    path: '/app/ms-fitnote-controller.jar'
    shouldExist: true
  - name: 'Config File'
    path: '/app/config.yml'
    shouldExist: true
  - name: 'Tessdata File'
    path: '/app/tessdata'

metadataTest:
  entrypoint: [ "java", "-jar", "/app/ms-fitnote-controller.jar", "server", "/app/config.yml" ]
